# example netlify.toml
[build]
  command = "# no build command"
  functions = "netlify/functions"
  publish = "."

[dev]
  autoLaunch = false

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["express","@sparticuz/chromium"]

[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"