[functions]
  external_node_modules = ["express","@sparticuz/chromium", "puppeteer-core", "ssh2-sftp-client"]
  node_bundler = "esbuild"
[[redirects]]
  force = true
  from = "/api/*"
  status = 200
  to = "/.netlify/functions/api/:splat"